### ISSUE TITLE
复现准确率低、处理数据问题

### ISSUE THREAD

**Issue by MynameisXU** [xyz189411yt/C4MMD#3]
1. 在data_divide.py时，
     chinese_text_data, _ = read_file(f'{load_path}/C_text.csv', 'Chinese/', chinese=True) 
     报错 UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 42: invalid start byte。
     所以我将 28行 加入了,errors='ignore' 变为 with open(file_name, 'r', encoding='utf-8', errors='ignore') as f: 
     
     2. 在CoT_module.py时
      ImageFile.LOAD_TRUNCATED_IMAGES = True
      
      torch.set_grad_enabled(False)
      
      # Set seed before initializing model.
      # set_seed(training_args.seed)
      model_local_path = '/data03/Sxd_Grp/TianY_99/LiuX/internlm-xcomposer-7b'
      device = 'cuda:5'
      
      from transformers import AutoModel
      
      model = AutoModel.from_pretrained(
                  model_local_path, trust_remote_code=True
              ).cuda().eval()
      tokenizer = AutoTokenizer.from_pretrained(
              model_local_path, trust_remote_code=True
          )
      model.tokenizer = tokenizer
      model.config.max_length = 100

复现结果在验证集上只有80%左右, 猜测可能原因：

         1. encoding='utf-8', errors='ignore' 导致数据处理有问题，而导致最后复现结果低。
         2. 在CoT_module.py对xcomposer-7b模型初始化时与作者初始化的一些参数不同（比如原作者设置 set_seed(training_args.seed)，但是我没有），导致最后复现结果低。
         3. 在CoT_module.py中的是internlm-xcomposer-7b 还是internlm-xcomposer-vl-7b呢?( 我复现时用的前者)

    期待作者回复，非常感谢！

**Comment by xyz189411yt** [comment]
针对你的三个可能的猜测：
1. 针对utf-8编码格式报错的问题，可能会对最终数据形式有一定影响。因为该问题可能导致模型对文本进行编码和分词时遇到异常。但是考虑到你在验证集上有80%左右的准确率，我猜测并不存在严重的编码格式问题。若想解决该问题，可以先将数据集文件编码格式修改为 utf-8，之后再做数据分割。
2. 针对模型初始化问题，你所提到的 set_seed(training_args.seed) 可能的确会造成一定的偏差，但偏差大小需要对 internlm-xcomposer-7b输出结果进行进一步评估。不过总的来说我认为偏差在2%左右都是可以接受的。
3. 我们用的模型是 internlm-xcomposer-7b。

总结：较小的结果偏差是正常的，因为涉及到很多参数的不同（硬件参数以及软件参数，例如CUDA版本，环境版本等）。如果想进一步缩短差距，可以优先考虑第二条，设置相同的随机种子进行进一步测试。同时可以留意一下C4MMD_train.py文件的tokenizer部分（检查第一条对分词的影响）。

**Comment by MynameisXU** [comment]
对代码做部分修改后，复现结果依然在80%左右。请问作者是否保留了CoT_module.py生成的三组数据new_train_data.json、new_test_data.json、new_val_data.json。我想以你提供的数据训练C4MMD_train.py，以此检验是C4MMD_train.py中的问题 还是 CoT_module.py的问题。

**Comment by MynameisXU** [comment]
> 针对你的三个可能的猜测：
> 
> 1. 针对utf-8编码格式报错的问题，可能会对最终数据形式有一定影响。因为该问题可能导致模型对文本进行编码和分词时遇到异常。但是考虑到你在验证集上有80%左右的准确率，我猜测并不存在严重的编码格式问题。若想解决该问题，可以先将数据集文件编码格式修改为 utf-8，之后再做数据分割。
> 2. 针对模型初始化问题，你所提到的 set_seed(training_args.seed) 可能的确会造成一定的偏差，但偏差大小需要对 internlm-xcomposer-7b输出结果进行进一步评估。不过总的来说我认为偏差在2%左右都是可以接受的。
> 3. 我们用的模型是 internlm-xcomposer-7b。
> 
> 总结：较小的结果偏差是正常的，因为涉及到很多参数的不同（硬件参数以及软件参数，例如CUDA版本，环境版本等）。如果想进一步缩短差距，可以优先考虑第二条，设置相同的随机种子进行进一步测试。同时可以留意一下C4MMD_train.py文件的tokenizer部分（检查第一条对分词的影响）。

修改部分代码重新实验，结果依然是80%左右。请问作者是否保留了CoT_module.py生成的三组数据new_train_data.json、new_test_data.json、new_val_data.json，我想使用你的数据重新训练C4MMD_train.py，以此检验是CoT_module.py中的问题 还是C4MMD_train.py中的问题

**Comment by xyz189411yt** [comment]
没有问题，请给我你一个在用的邮件，我会将我的三组数据整理好后发你 :)

**Comment by MynameisXU** [comment]
> 没有问题，请给我你一个在用的邮件，我会将我的三组数据整理好后发你 :)
太感谢了!!! 1161256911@qq.com

**Comment by snow-like-kk** [comment]
您好，请问可以分享一下您更新后的CoT_module.py代码吗？我不清楚InternLM-XComposer最新的demo在哪里可以找到

**Comment by believe81** [comment]
> 您好，请问可以分享一下您更新后的CoT_module.py代码吗？我不清楚InternLM-XComposer最新的demo在哪里可以找到

好的，这是在测试集上的代码，你改一下路径，就可以
[CoT_module_test.zip](https://github.com/user-attachments/files/17529822/CoT_module_test.zip)
在训练集和验证集上运行了

**Comment by snow-like-kk** [comment]
> > 您好，请问可以分享一下您更新后的CoT_module.py代码吗？我不清楚InternLM-XComposer最新的demo在哪里可以找到
> 
> 好的，这是在测试集上的代码，你改一下路径，就可以 [CoT_module_test.zip](https://github.com/user-attachments/files/17529822/CoT_module_test.zip) 在训练集和验证集上运行了

太感谢啦！！！

**Comment by snow-like-kk** [comment]
> > 没有问题，请给我你一个在用的邮件，我会将我的三组数据整理好后发你 :)
> > [1161256911@qq.com](mailto:1161256911@qq.com)
> > 太感谢了!!! 感动到哭泣哈哈哈，再次感谢原作者！！
您好，请问可以将这三组数据也share给我一下吗？我这里出了很多问题？

**Comment by believe81** [comment]
> > > 没有问题，请给我你一个在用的邮件，我会将我的三组数据整理好后发你 :)
> > > [1161256911@qq.com](mailto:1161256911@qq.com)
> > > 太感谢了!!! 感动到哭泣哈哈哈，再次感谢原作者！！
> > > 您好，请问可以将这三组数据也share给我一下吗？我这里出了很多问题？

[C4MMD_data.zip](https://github.com/user-attachments/files/17583007/C4MMD_data.zip)

**Comment by xyz189411yt** [comment]
> > 没有问题，请给我你一个在用的邮件，我会将我的三组数据整理好后发你 :)
> > [1161256911@qq.com](mailto:1161256911@qq.com)
> > 太感谢了!!! 感动到哭泣哈哈哈，再次感谢原作者！！

请问最后能够复现我们论文中的结果了吗？如果可以的话我会关闭这个问题 :)

**Comment by believe81** [comment]
> > > 没有问题，请给我你一个在用的邮件，我会将我的三组数据整理好后发你 :)
> > > [1161256911@qq.com](mailto:1161256911@qq.com)
> > > 太感谢了!!! 感动到哭泣哈哈哈，再次感谢原作者！！
> 
> 请问最后能够复现我们论文中的结果了吗？如果可以的话我会关闭这个问题 :)

我已经复现成功，感谢作者！！可以关闭

**Comment by Wu-Guo-Xiang** [comment]
> > 您好，请问可以分享一下您更新后的CoT_module.py代码吗？我不清楚InternLM-XComposer最新的demo在哪里可以找到
> 
> 好的，这是在测试集上的代码，你改一下路径，就可以 [CoT_module_test.zip](https://github.com/user-attachments/files/17529822/CoT_module_test.zip) 在训练集和验证集上运行了

@believe81 你好，请问你可以分享一下你复现成功的代码吗
